version: "3"

services:
  user-api:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:mypass@db:5432/mydb
      - EMAIL_SERVER_URL=http://email-server:80
    ports:
      - "8000:80"
    networks:
      - api_network

  db:
    image: postgres:15-alpine
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb
    networks:
      - api_network
    ports:
      - 5432:5432

  email-server:
    build:
      context: .
      dockerfile: Dockerfile.email_server_mock
    restart: always
    ports:
      - "8001:80"
    networks:
      - api_network

networks:
  api_network:
