version: "3"

services:
  user-api:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:mypass@localhost:5433/mydb
    ports:
      - "8000:80"
    networks:
      - api_network

  db:
    image: postgres:15-alpine
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data/
    expose:
      - 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=mydb
    networks:
      - api_network

networks:
  api_network:
